/* =========================================================
   RUDRA BHAKTI — FIREBASE REALTIME DATABASE SERVICE
   js/firebase-service.js
   ========================================================= */

import {
  db
} from "./firebase.js";

import {
  ref,
  get,
  set,
  push,
  update,
  query,
  orderByChild,
  equalTo,
  limitToLast,
  serverTimestamp
} from
  "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";


/* =========================================================
   DATABASE PATHS
   ========================================================= */

const PATHS = {
  reels: "reels",
  questions: "questions",
  feedback: "feedback",
  admins: "admins"
};


/* =========================================================
   REEL SERVICES
   ========================================================= */

/**
 * Get one Reel.
 *
 * Example:
 * getReel("RB0001")
 */
export async function getReel(reelId) {
  if (!reelId) {
    throw new Error("Reel ID is required.");
  }

  const snapshot = await get(
    ref(db, `${PATHS.reels}/${reelId}`)
  );

  if (!snapshot.exists()) {
    return null;
  }

  return {
    id: reelId,
    ...snapshot.val()
  };
}


/**
 * Get all Reels.
 * Admin use.
 */
export async function getAllReels() {
  const snapshot = await get(
    ref(db, PATHS.reels)
  );

  if (!snapshot.exists()) {
    return [];
  }

  const data = snapshot.val();

  return Object.entries(data).map(
    ([id, reel]) => ({
      id,
      ...reel
    })
  );
}


/**
 * Get active Reels.
 */
export async function getActiveReels() {
  const reelsQuery = query(
    ref(db, PATHS.reels),
    orderByChild("feedbackEnabled"),
    equalTo(true)
  );

  const snapshot =
    await get(reelsQuery);

  if (!snapshot.exists()) {
    return [];
  }

  const data = snapshot.val();

  return Object.entries(data)
    .map(([id, reel]) => ({
      id,
      ...reel
    }))
    .filter(
      (reel) =>
        reel.status === "active"
    );
}


/**
 * Create a Reel.
 *
 * Reel ID should be generated by the admin UI,
 * e.g. RB0001.
 */
export async function createReel(
  reel
) {
  if (!reel?.reelId) {
    throw new Error(
      "Reel ID is required."
    );
  }

  const reelRef = ref(
    db,
    `${PATHS.reels}/${reel.reelId}`
  );

  const existing =
    await get(reelRef);

  if (existing.exists()) {
    throw new Error(
      `Reel ${reel.reelId} already exists.`
    );
  }

  const reelData = {
    reelId:
      String(reel.reelId),

    title:
      reel.title?.trim() ||
      "Untitled Reel",

    reelUrl:
      reel.reelUrl?.trim() || "",

    thumbnailUrl:
      reel.thumbnailUrl?.trim() || "",

    status:
      reel.status || "active",

    feedbackEnabled:
      reel.feedbackEnabled !== false,

    createdAt:
      serverTimestamp(),

    updatedAt:
      serverTimestamp()
  };

  await set(
    reelRef,
    reelData
  );

  return {
    id: reel.reelId,
    ...reelData
  };
}


/**
 * Update Reel.
 */
export async function updateReel(
  reelId,
  changes
) {
  if (!reelId) {
    throw new Error(
      "Reel ID is required."
    );
  }

  const reelRef = ref(
    db,
    `${PATHS.reels}/${reelId}`
  );

  await update(
    reelRef,
    {
      ...changes,
      updatedAt:
        serverTimestamp()
    }
  );

  return getReel(reelId);
}


/**
 * Enable / disable a Reel.
 */
export async function setReelStatus(
  reelId,
  active
) {
  return updateReel(
    reelId,
    {
      status:
        active
          ? "active"
          : "inactive",

      feedbackEnabled:
        Boolean(active)
    }
  );
}


/* =========================================================
   QUESTION SERVICES
   ========================================================= */

/**
 * Get one Question.
 */
export async function getQuestion(
  questionId
) {
  if (!questionId) {
    throw new Error(
      "Question ID is required."
    );
  }

  const snapshot = await get(
    ref(
      db,
      `${PATHS.questions}/${questionId}`
    )
  );

  if (!snapshot.exists()) {
    return null;
  }

  return {
    id: questionId,
    ...snapshot.val()
  };
}


/**
 * Get active Questions.
 *
 * RTDB does not automatically sort numeric
 * "order" values the same way Firestore does,
 * so we sort them after reading.
 */
export async function getActiveQuestions() {
  const snapshot =
    await get(
      ref(db, PATHS.questions)
    );

  if (!snapshot.exists()) {
    return [];
  }

  const data =
    snapshot.val();

  return Object.entries(data)
    .map(([id, question]) => ({
      id,
      ...question
    }))
    .filter(
      (question) =>
        question.active === true
    )
    .sort(
      (a, b) =>
        Number(a.order || 0) -
        Number(b.order || 0)
    );
}


/**
 * Get all Questions.
 * Admin use.
 */
export async function getAllQuestions() {
  const snapshot =
    await get(
      ref(db, PATHS.questions)
    );

  if (!snapshot.exists()) {
    return [];
  }

  const data =
    snapshot.val();

  return Object.entries(data)
    .map(([id, question]) => ({
      id,
      ...question
    }))
    .sort(
      (a, b) =>
        Number(a.order || 0) -
        Number(b.order || 0)
    );
}


/* =========================================================
   FEEDBACK SERVICES
   ========================================================= */

/**
 * Submit public feedback.
 *
 * A random Firebase push ID is generated.
 */
export async function submitFeedback(
  feedback
) {
  if (!feedback) {
    throw new Error(
      "Feedback data is required."
    );
  }

  if (!feedback.reelId) {
    throw new Error(
      "Reel ID is required."
    );
  }

  if (!feedback.sessionId) {
    throw new Error(
      "Session ID is required."
    );
  }

  if (
    !feedback.answers ||
    typeof feedback.answers !== "object"
  ) {
    throw new Error(
      "Answers are required."
    );
  }


  /*
   * Generate unique feedback ID.
   */
  const feedbackListRef =
    ref(db, PATHS.feedback);

  const newFeedbackRef =
    push(feedbackListRef);

  const feedbackId =
    newFeedbackRef.key;


  /*
   * Data saved to RTDB.
   */
  const feedbackData = {
    feedbackId,

    reelId:
      String(feedback.reelId),

    sessionId:
      String(feedback.sessionId),

    answers:
      feedback.answers || {},

    questionTiming:
      feedback.questionTiming || {},

    engagement:
      feedback.engagement || {},

    typing:
      feedback.typing || {},

    device:
      feedback.device || {},

    startedAt:
      feedback.startedAt || null,

    completedAt:
      feedback.completedAt || null,

    totalDurationMs:
      Number(
        feedback.totalDurationMs || 0
      ),

    createdAt:
      serverTimestamp()
  };


  await set(
    newFeedbackRef,
    feedbackData
  );


  return {
    id: feedbackId,
    ...feedbackData
  };
}


/* =========================================================
   ADMIN FEEDBACK SERVICES
   ========================================================= */

/**
 * Get feedback for one Reel.
 *
 * Admin use.
 */
export async function getFeedbackByReel(
  reelId,
  maxResults = 100
) {
  if (!reelId) {
    throw new Error(
      "Reel ID is required."
    );
  }

  const feedbackQuery =
    query(
      ref(db, PATHS.feedback),

      orderByChild(
        "reelId"
      ),

      equalTo(reelId),

      limitToLast(
        maxResults
      )
    );

  const snapshot =
    await get(feedbackQuery);

  if (!snapshot.exists()) {
    return [];
  }

  const data =
    snapshot.val();

  return Object.entries(data)
    .map(([id, feedback]) => ({
      id,
      ...feedback
    }))
    .reverse();
}


/**
 * Get latest feedback.
 *
 * RTDB ordering is based on createdAt.
 */
export async function getLatestFeedback(
  maxResults = 50
) {
  const feedbackQuery =
    query(
      ref(db, PATHS.feedback),

      orderByChild(
        "createdAt"
      ),

      limitToLast(
        maxResults
      )
    );

  const snapshot =
    await get(feedbackQuery);

  if (!snapshot.exists()) {
    return [];
  }

  const data =
    snapshot.val();

  return Object.entries(data)
    .map(([id, feedback]) => ({
      id,
      ...feedback
    }))
    .reverse();
}


/* =========================================================
   ADMIN RECORD
   ========================================================= */

/**
 * Get admin record.
 *
 * Actual security will later be enforced through
 * Firebase Authentication + RTDB Security Rules.
 */
export async function getAdminRecord(
  uid
) {
  if (!uid) {
    return null;
  }

  const snapshot =
    await get(
      ref(
        db,
        `${PATHS.admins}/${uid}`
      )
    );

  if (!snapshot.exists()) {
    return null;
  }

  return {
    uid,
    ...snapshot.val()
  };
}


/* =========================================================
   UTILITY FUNCTIONS
   ========================================================= */

/**
 * Convert Firebase timestamp / Date /
 * ISO string into JavaScript Date.
 */
export function toJSDate(
  value
) {
  if (!value) {
    return null;
  }

  if (
    value instanceof Date
  ) {
    return value;
  }

  if (
    typeof value === "number"
  ) {
    const date =
      new Date(value);

    return Number.isNaN(
      date.getTime()
    )
      ? null
      : date;
  }

  const date =
    new Date(value);

  return Number.isNaN(
    date.getTime()
  )
    ? null
    : date;
}


/**
 * Format milliseconds.
 */
export function formatDuration(
  milliseconds
) {
  const ms =
    Number(milliseconds) || 0;

  if (ms <= 0) {
    return "—";
  }

  const totalSeconds =
    Math.round(ms / 1000);

  const minutes =
    Math.floor(
      totalSeconds / 60
    );

  const seconds =
    totalSeconds % 60;

  if (minutes > 0) {
    return `${minutes}m ${seconds}s`;
  }

  return `${seconds}s`;
}


/* =========================================================
   DATABASE STRUCTURE
   =========================================================

   reels/
     RB0001/
       reelId
       title
       reelUrl
       thumbnailUrl
       status
       feedbackEnabled
       createdAt
       updatedAt

   questions/
     Q001/
       questionId
       questionText
       hindiText
       type
       required
       order
       active
       options/

   feedback/
     -AUTO_GENERATED_ID/
       feedbackId
       reelId
       sessionId
       answers/
       questionTiming/
       engagement/
       typing/
       device/
       startedAt
       completedAt
       totalDurationMs
       createdAt

   admins/
     FIREBASE_AUTH_UID/
       role
       active

   ========================================================= */
